# Generated by Django 5.2.4 on 2025-09-14 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_attendance_quiz_attempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('engaged', models.BooleanField(default=False)),
                ('quiz_completed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudentEngagementMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quizzes_taken', models.PositiveIntegerField(default=0)),
                ('total_quiz_score', models.FloatField(default=0.0)),
                ('average_quiz_score', models.FloatField(default=0.0)),
                ('performance_category', models.CharField(choices=[('danger', 'In Danger (<50%)'), ('good', 'Good (50-70%)'), ('excellent', 'Excellent (>70%)')], default='good', max_length=10)),
                ('consecutive_missed_quizzes', models.PositiveIntegerField(default=0)),
                ('last_quiz_date', models.DateField(blank=True, null=True)),
                ('intervention_email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_metrics', to='courses.course')),
                ('student', models.OneToOneField(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-average_quiz_score'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
