# Generated by Django 5.2.4 on 2025-08-18 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Course name (e.g., Computer Science 3002)', max_length=200)),
                ('code', models.CharField(help_text='Course code (e.g., CSC3002S)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Course description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this course currently active?')),
                ('lecturer', models.ForeignKey(help_text='Lecturer who created this course', limit_choices_to={'user_type': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CSVUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Original CSV file name', max_length=255)),
                ('students_added', models.PositiveIntegerField(default=0, help_text='Number of students successfully added')),
                ('students_skipped', models.PositiveIntegerField(default=0, help_text='Number of students skipped (duplicates)')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('batch_id', models.CharField(help_text='Unique batch identifier', max_length=100)),
                ('course', models.ForeignKey(help_text='Course students were added to', on_delete=django.db.models.deletion.CASCADE, related_name='csv_uploads', to='courses.course')),
                ('uploaded_by', models.ForeignKey(help_text='Lecturer who uploaded the CSV', limit_choices_to={'user_type': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CSV Upload Log',
                'verbose_name_plural': 'CSV Upload Logs',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this enrollment currently active?')),
                ('csv_upload_batch', models.CharField(blank=True, help_text='Batch identifier for CSV uploads', max_length=100)),
                ('course', models.ForeignKey(help_text='Course the student is enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('enrolled_by', models.ForeignKey(blank=True, help_text='Lecturer who enrolled this student', limit_choices_to={'user_type': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student enrolled in the course', limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('course', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Topic name (e.g., Variables and Data Types)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Topic description')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of this topic within the course (1, 2, 3...)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this topic currently available?')),
                ('course', models.ForeignKey(help_text='Course this topic belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.course')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['course', 'order', 'name'],
                'unique_together': {('course', 'order')},
            },
        ),
    ]
