# Generated by Django 5.2.4 on 2025-09-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_attendance_quiz_attempt'),
        ('courses', '0003_attendance'),
    ]

    operations = [
    ]
