# Generated by Django 5.2.4 on 2025-09-13 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrollment_code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_students',
        ),
    ]
