# Generated by Django 5.2.4 on 2025-09-20 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_quiz', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureslide',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_slides', to='courses.topic'),
        ),
        migrations.AddField(
            model_name='lectureslide',
            name='uploaded_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adaptivequiz',
            name='lecture_slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_quizzes', to='ai_quiz.lectureslide'),
        ),
        migrations.AddField(
            model_name='studentadaptiveprogress',
            name='adaptive_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='ai_quiz.adaptivequiz'),
        ),
        migrations.AddField(
            model_name='studentadaptiveprogress',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adaptivequizattempt',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ai_quiz.studentadaptiveprogress'),
        ),
        migrations.AlterUniqueTogether(
            name='adaptivequiz',
            unique_together={('lecture_slide', 'difficulty')},
        ),
        migrations.AlterUniqueTogether(
            name='studentadaptiveprogress',
            unique_together={('student', 'adaptive_quiz')},
        ),
    ]
