# Generated by Django 5.2.4 on 2025-09-20 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_quiz', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptivequiz',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adaptivequiz',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adaptivequiz',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adaptivequiz',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
